version: '3.4'

services:
    apigateway:
        image: "apigateway:latest"
        ports:
            - "10000:80"
            - "10001:80"
        volumes:
            - ./ApiGateway/ocelot.json:/etc/ocelot/ocelot.json

    catalogapi:
        image: "catalogapi:dev"
        ports:
            - "3000:5001"
        environment:
            - ConnectionString=Server=sqldata,1433;Initial Catalog=CatalogService;User Id=sa;Password=Pass@word;TrustServerCertificate=True;Connection Timeout=5;
        depends_on: 
        - sqldata
        - eventbus
        restart: on-failure
    basketapi:
        image: "basketapi:dev"
        ports:
            - "4000:5002"
        depends_on:
            - basketdata
            - eventbus
        restart: on-failure
    sqldata:
        image: "microsoft/mssql-server-linux"
        environment: 
            - SA_PASSWORD=Pass@word
            - ACCEPT_EULA=Y
        ports:
            - "5433:1433"
    basketdata:
        image: "redis"
        ports:
            - "9080:6379"
    eventbus:
        image: "rabbitmq"
        ports: 
            - "5672:5672"
            - "15672:15672"
