version: '3.4'

services:
    catalogapi:
        image: "catalogapi:dev"
        ports:
            - "8081:5001"
        environment:
            - ConnectionString=Server=sqldata,1433;Initial Catalog=CatalogService;User Id=sa;Password=Pass@word;TrustServerCertificate=True;Connection Timeout=5;
        depends_on: 
        - sqldata
    sqldata:
        image: "microsoft/mssql-server-linux"
        environment: 
            - SA_PASSWORD=Pass@word
            - ACCEPT_EULA=Y
        ports:
            - "5433:1433"